#!/usr/bin/env bash

# create longer-lasting ssh tunnel with localhost.run (optional; requires private key './srvkey' generated by running 'ssh-keygen -t rsa' and having the public key 'srvkey.pub' added at 'https://admin.localhost.run/#/keys')
#sudo chmod 600 srvkey
#ssh -o "IdentitiesOnly=yes" -o "StrictHostKeyChecking=no" -i srvkey -R 80:localhost:5007 localhost.run 2>&1 &

# run the python server (expects that './data.txt' with ticket exports exists)
python3 server.py
